
create table if not exists lectures (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        title VARCHAR(255),
    summary VARCHAR(1024),
    course_order INT
    );
create table if not exists course_materials (
                                          id uuid default random_uuid() not null,
    content blob,
    original_file_name varchar(255),
    stored_file_path varchar(255),
    content_type varchar(255),
    file_size bigint,
    uploaded_at   TIMESTAMP,
    lecture_id bigint,
    primary key (id),
    foreign key (lecture_id) references lectures
    );

DROP TABLE IF EXISTS user_roles cascade;
DROP TABLE IF EXISTS users cascade    ;


CREATE TABLE IF NOT EXISTS users (
                                     id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     username  VARCHAR(50) NOT NULL UNIQUE,
    password  VARCHAR(255) NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    email     VARCHAR(120) NOT NULL UNIQUE,
    phone     VARCHAR(30) NOT NULL,
    role      VARCHAR(20) NOT NULL,
    enabled   BOOLEAN NOT NULL
    );;


CREATE TABLE IF NOT EXISTS user_roles (
                                          user_role_id INTEGER GENERATED ALWAYS AS IDENTITY,
                                          username VARCHAR(50) NOT NULL,
    role VARCHAR(50) NOT NULL,
    PRIMARY KEY (user_role_id),
    FOREIGN KEY (username) REFERENCES users(username)
    );
